---DATE DIM

CREATE TABLE DATE_DIM (
    DATE_DIM_ID NUMBER(*,0) PRIMARY KEY,
    RESERVATION_DATE DATE,
    RESERVATION_DAY_MONTH NUMBER(*,0),
    RESERVATION_MONTH NUMBER(*,0),
    RESERVATION_YEAR NUMBER(*,0),
    RESERVATION_QUARTER NUMBER(*,0)
);

CREATE SEQUENCE DATE_DIM_S;
CREATE OR REPLACE TRIGGER date_dim_on_insert
     BEFORE INSERT ON DATE_DIM
     FOR EACH ROW
BEGIN
     SELECT DATE_DIM_S.NEXTVAL
     INTO :NEW.DATE_DIM_ID
     FROM DUAL;
END;

--- PAYMENT_DIM

CREATE TABLE PAYMENT_DIM (
    PAYMENT_DIM_ID NUMBER(*,0) PRIMARY KEY,
    PAYMENT_ID NUMBER(*,0) NOT NULL,
    PAYMENT_DATE DATE,
    PAYMENT_AMOUNT NUMBER NOT NULL 
);

CREATE SEQUENCE PAYMENT_DIM_S;
CREATE OR REPLACE TRIGGER payment_dim_on_insert
     BEFORE INSERT ON PAYMENT_DIM
     FOR EACH ROW
BEGIN
     SELECT PAYMENT_DIM_S.NEXTVAL
     INTO :NEW.PAYMENT_DIM_ID
     FROM DUAL;
END;


--- CLIENT_DIM 

CREATE TABLE CLIENT_DIM (
    CLIENT_DIM_ID NUMBER(*,0) PRIMARY KEY,
    CLIENT_ID NUMBER(*,0) NOT NULL,
    FIRST_NAME VARCHAR(80),
    LAST_NAME VARCHAR(80),
    PHONE_NUMBER VARCHAR(14),
    EMAIL VARCHAR(80),
    COUNTRY VARCHAR(80),
    CITY VARCHAR(100),
);

CREATE SEQUENCE CLIENT_DIM_S;
CREATE OR REPLACE TRIGGER client_dim_on_insert
     BEFORE INSERT ON CLIENT_DIM
     FOR EACH ROW
BEGIN
     SELECT CLIENT_DIM_S.NEXTVAL
     INTO :NEW.CLIENT_DIM_ID
     FROM DUAL;
END;

--- FLIGHT_DIM

CREATE TABLE FLIGHT_DIM (
    FLIGHT_DIM_ID NUMBER(*,0) PRIMARY KEY,
    FLIGHT_ID NUMBER(*,0) NOT NULL,
    DEPARTURE_DATE DATE,
    ARRIVAL_DATE DATE,
    DEPARTURE_AIRPORT_NAME VARCHAR(100),    ---sa kog polece
    ARRIVAL_AIRPORT_NAME VARCHAR(100),      ---na koji slece
    DEPARTURE_AIRPORT_LOCATION VARCHAR(100),---adresa aerodroma sa kog polece
    ARRIVAL_AIRPOR_LOCATION VARCHAR(100),   ---adresa aerodroma na koji slece
    AIRLINE_NAME VARCHAR(80),
    AIRLINE_COUNTRY VARCHAR(80),            ---zemlja iz koje je avio kompanija
    AIRCRAFT_NAME VARCHAR(100),
    AIRCRAFT_CAPACITY NUMBER
);

CREATE SEQUENCE FLIGHT_DIM_S;
CREATE OR REPLACE TRIGGER flight_dim_on_insert
     BEFORE INSERT ON FLIGHT_DIM
     FOR EACH ROW
BEGIN
     SELECT FLIGHT_DIM_S.NEXTVAL
     INTO :NEW.FLIGHT_DIM_ID
     FROM DUAL;
END;

--- RESERVATION_FACT

CREATE TABLE RESERVATION_FACT (
    RESERVATION_ID NUMBER(*,0),
    CLIENT_DIM_ID NUMBER(*,0),
    DATE_DIM_ID NUMBER(*,0),
    FLIGHT_DIM_ID NUMBER(*,0),
    PAYMENT_DIM_ID NUMBER(*,0),
    SEAT_NUMBER VARCHAR(4),
    TRAVEL_CLASS VARCHAR(20),
    PRICE NUMBER,
    FLIGHT_LENGTH NUMBER        --- duzina leta u satima ili minutima?
);
