--- Convert datetime to format: dd-MM-yyyy
SELECT RESERVATION_DATE,
FORMAT (RESERVATION_DATE, 'dd-MM-yyyy') AS DATA_DATA
	FROM RESERVATIONS;

--- Select only DATA_DATA (dd-MM-yyyy formated string):
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT RESERVATION_ID, DATA_DATA
FROM (
	SELECT RESERVATION_ID, RESERVATION_DATE, 
	FORMAT (RESERVATION_DATE, 'dd-MM-yyyy') AS DATA_DATA
		FROM RESERVATIONS
) AS PODACI;

--- Konacno ono sto mi i treba, ****** sql datumi:
SELECT RESERVATION_ID, DATA_DATA, DATE_MONTH_DAY, DATE_MONTH, DATE_YEAR, DATE_QUARTER
FROM (
	SELECT RESERVATION_ID, RESERVATION_DATE,
	DAY(RESERVATION_DATE) AS DATE_MONTH_DAY,
	MONTH(RESERVATION_DATE) AS DATE_MONTH,
	YEAR(RESERVATION_DATE) AS DATE_YEAR,
	((MONTH(RESERVATION_DATE) - 1) / 3) + 1 AS DATE_QUARTER,
	FORMAT (RESERVATION_DATE, 'dd-MM-yyyy') AS DATA_DATA
		FROM RESERVATIONS
) AS PODACI;

--- Upisivanje podataka iz sql server u sqldeveloper tabelu DATE_DIM:
insert into DATE_DIM (
	RESERVATION_DATE,
	RESERVATION_DAY_MONTH,
	RESERVATION_MONTH,
	RESERVATION_YEAR,
	RESERVATION_QUARTER
) VALUES (
	to_date('${RESERVATION_DATE}','dd-MM-yyyy'), 
	${DATE_MONTH_DAY},
	${DATE_MONTH}, 
	${DATE_YEAR},
	${RESERVATION_QUARTER}
)

--- Naredba za praznjenje sadrzaja tabele:
TRUNCATE TABLE DATE_DIM;

--- Naredba za postavljanje trenutne vrednosti sekvence:
DROP SEQUENCE DATE_DIM_S;
CREATE SEQUENCE DATE_DIM_S;

--- Naredba za ucitavanje podataka za dimenziju PAYMENT_DIM iz sqlserver:
SELECT PAYMENT_ID, PAYMENT_DATE_FORM, PAYMENT_AMOUNT FROM (
SELECT PAYMENT_ID, PAYMENT_DATE, PAYMENT_AMOUNT,
FORMAT (PAYMENT_DATE, 'dd-MM-yyyy') AS PAYMENT_DATE_FORM
	FROM PAYMENTS) AS PODACI;

--- Naredba za proveru da li se trenutni AVRO podatak nalazi vec
--- unutar sqldeveloper baze podataka:
SELECT 
    PAYMENT_DIM_ID AS PAYMENT_DIM_ID_R, 
    PAYMENT_ID AS PAYMENT_ID_R, 
    PAYMENT_DATE AS PAYMENT_DATE_R, 
    PAYMENT_AMOUNT AS PAYMENT_AMOUNT_R 
FROM PAYMENT_DIM WHERE PAYMENT_DIM_ID = 1;


--- Naredba za dodavanje novog objekata u PAYMENT_DIM tabelu:
INSERT INTO PAYMENT_DIM (
	PAYMENT_ID,
	PAYMENT_DATE,
	PAYMENT_AMOUNT
) VALUES (
	${PAYMENT_ID},
	to_date('${PAYMENT_DATE}', 'dd-MM-yyyy'),
	${PAYMENT_AMOUNT}
)		--- ne dodaj ; !!!

--- Naredba za update vec postojeceg objekta u PAYMENT_DIM tabeli:
UPDATE PAYMENT_DIM 
SET PAYMENT_DATE = to_date('${PAYMENT_DATE}', 'dd-MM-yyyy'),
    PAYMENT_AMOUNT = ${PAYMENT_AMOUNT}
WHERE PAYMENT_DIM_ID = ${PAYMENT_DIM_ID_R}

--- Naredba za ucitavanje podataka za dimenziju CLIENT_DIM iz sqlserver:
SELECT 
	CLIENT_ID AS CLIENT_ID,
	FIRST_NAME AS FIRST_NAME,
	LAST_NAME AS LAST_NAME,
	PHONE_NUMBER AS PHONE_NUMBER,
	EMAIL_ADDRESS AS EMAIL,
	COUNTRY AS COUNTRY,
	CITY AS CITY
FROM CLIENTS;


--- Naredba za ucitavanje podataka iz sqldeveloper baze podataka:
SELECT 
    CLIENT_DIM_ID AS CLIENT_DIM_ID_R,
    CLIENT_ID AS CLIENT_ID_R,
    FIRST_NAME AS FIRST_NAME_R,
    LAST_NAME AS LAST_NAME_R,
    PHONE_NUMBER AS PHONE_NUMBER_R,
    EMAIL AS EMAIL_R,
    COUNTRY AS COUNTRY_R,
    CITY AS CITY_R
FROM CLIENT_DIM WHERE CLIENT_ID = 1


--- Naredba za kreiranje novog objekta tabele CLIENT_DIM u sqldeveloper:
INSERT INTO CLIENT_DIM (
	CLIENT_ID,
	FIRST_NAME,
	LAST_NAME,
	PHONE_NUMBER,
	EMAIL,
	COUNTRY,
	CITY
) VALUES (
	${CLIENT_ID},
	'${FIRST_NAME}',
	'${LAST_NAME}',
	'${PHONE_NUMBER}',
	'${EMAIL}',
	'${COUNTRY}',
	'${CITY}'
)


--- Naredba za update vec postojeceg objekta CLIENT_DIM-a:
UPDATE CLIENT_DIM
SET FIRST_NAME = '${FIRST_NAME}',
	LAST_NAME = '${LAST_NAME}',
	PHONE_NUMBER = '${PHONE_NUMBER}',
	EMAIL = '${EMAIL}',
	COUNTRY = '${COUNTRY}',
	CITY = '${CITY}',
WHERE CLIENT_DIM_ID = ${CLIENT_DIM_ID_R}


--- Skripta za ucitavanje podataka o letovima:
SELECT 
	FLIGHT_ID AS FLIGHT_ID,
	FORMATED_DEPARTURE_DATE AS DEPARTURE_DATE,
	FORMATED_ARRIVAL_DATE AS ARRIVAL_DATE,
	AIRPORT_ID AS DEPARTURE_AIRPORT_ID,
	ARRIVAL_AIRPORT_ID AS ARRIVAL_AIRPORT_ID,
	AIRLINE_ID AS AIRLINE_ID,
	AIRCRAFT_ID AS AIRCRAFT_ID
FROM (
	SELECT 
		FLIGHT_ID,
		DEPARTURE_DATE_TIME,
		ARRIVAL_DATE_TIME,
		AIRLINE_ID,
		AIRCRAFT_ID,
		AIRPORT_ID,
		ARRIVAL_AIRPORT_ID,
	FORMAT (DEPARTURE_DATE_TIME, 'dd-MM-yyyy hh:MM:ss') AS FORMATED_DEPARTURE_DATE,
	FORMAT (ARRIVAL_DATE_TIME, 'dd-MM-yyyy hh:MM:ss') AS FORMATED_ARRIVAL_DATE
	FROM FLIGHTS) 
AS PODACI;


--- Za dopunu tabele FLIGHT_DIM sa podacima o letovima:
SELECT 
	AIRPORT_NAME AS ARRIVAL_AIRPORT_NAME,
	AIRPORT_LOCATION AS ARRIVAL_AIRPORT_LOCATION
FROM AIRPORTS WHERE AIRPORT_ID = ${ARRIVAL_AIRPORT_ID}

--- Za dopunu tabele FLIGHT_DIM sa podacima o avio-kompaniji:
SELECT 
	AIRLINE_NAME AS AIRLINE_NAME,
	AIRLINE_COUNTRY AS AIRLINE_COUNTRY
FROM AIRLINES WHERE AIRLINE_ID = 2

--- Za dopunu tabele FLIGHT_DIM sa podacima o avionu:
SELECT 
	AIRCRAFT_NAME AS AIRCRAFT_NAME,
	AIRCRAFT_CAPACITY AS AIRCRAFT_CAPACITY
FROM AIRCRAFTS WHERE AIRCRAFT_ID = 2


--- Za proveru da li se podatak iz sqlserver-a nalazi vec u 
--- sqldeveloper bazi podataka:
SELECT 
	FLIGHT_DIM_ID AS FLIGHT_DIM_ID_R,
	DEPARTURE_DATE AS DEPARTURE_DATE_R, 
	ARRIVAL_DATE AS ARRIVAL_DATE_R,
	DEPARTURE_AIRPORT_NAME AS DEPARTURE_AIRPORT_NAME_R,
	ARRIVAL_AIRPORT_NAME AS ARRIVAL_AIRPORT_NAME_R,
	DEPARTURE_AIRPORT_LOCATION AS DEPARTURE_AIRPORT_LOCATION_R,
	ARRIVAL_AIRPORT_LOCATION AS ARRIVAL_AIRPORT_LOCATION_R,
	AIRLINE_NAME AS AIRLINE_NAME_R,
	AIRLINE_COUNTRY AS AIRLINE_COUNTRY_R,
	AIRCRAFT_NAME AS AIRCRAFT_NAME_R,
	AIRCRAFT_CAPACITY AS AIRCRAFT_CAPACITY_R
FROM FLIGHT_DIM WHERE FLIGHT_ID = ${FLIGHT_ID}


--- Za dodavanje novog objekta u tabelu FLIGHT_DIM:
INSERT INTO FLIGHT_DIM (
	FLIGHT_ID,
	DEPARTURE_DATE,
	ARRIVAL_DATE,
	DEPARTURE_AIRPORT_NAME,
	ARRIVAL_AIRPORT_NAME,
	DEPARTURE_AIRPORT_LOCATION,
	ARRIVAL_AIRPORT_LOCATION,
	AIRLINE_NAME,
	AIRLINE_COUNTRY,
	AIRCRAFT_NAME,
	AIRCRAFT_CAPACITY
) VALUES (
	${FLIGHT_ID},
	to_date('${DEPARTURE_DATE}', 'dd-MM-yyyy hh:MM:ss'),
	to_date('${ARRIVAL_DATE}'),
	'${DEPARTURE_AIRPORT_NAME}',
	'${ARRIVAL_AIRPORT_NAME}',
	'${DEPARTURE_AIRPORT_LOCATION}',
	'${ARRIVAL_AIRPORT_LOCATION}',
	'${AIRLINE_NAME}',
	'${AIRLINE_COUNTRY}',
	'${AIRCRAFT_NAME}',
	${AIRCRAFT_CAPACITY},
)

--- Naredba za update vec postojeceg objekta FLIGHT_DIM-a:
UPDATE FLIGHT_DIM
SET DEPARTURE_DATE = to_date('${DEPARTURE_DATE}', 'dd-MM-yyyy hh:MM:ss'),
	ARRIVAL_DATE = to_date('${ARRIVAL_DATE}', 'dd-MM-yyyy hh:MM:ss'),
	DEPARTURE_AIRPORT_NAME = '${DEPARTURE_AIRPORT_NAME}'
	ARRIVAL_AIRPORT_NAME = '${ARRIVAL_AIRPORT_NAME}'
	DEPARTURE_AIRPORT_LOCATION = '${DEPARTURE_AIRPORT_LOCATION}'
	ARRIVAL_AIRPORT_LOCATION = '${ARRIVAL_AIRPORT_LOCATION}'
	AIRLINE_NAME = '${AIRLINE_NAME}'
	AIRLINE_COUNTRY = '${AIRLINE_COUNTRY}'
	AIRCRAFT_NAME = '${AIRCRAFT_NAME}'
	AIRCRAFT_CAPACITY = ${AIRCRAFT_CAPACITY}
WHERE FLIGHT_ID = ${FLIGHT_ID}


--- Naredba za ucitavanje podataka o rezervacijama iz sqldeveloper-a:
SELECT 
	RESERVATION_ID AS RESERVATION_ID,
	FORMAT(RESERVATION_DATE, 'dd-MM-yyyy') AS RESERVATION_DATE,
	SEAT_NUMBER AS SEAT_NUMBER,
	FLIGHT_ID AS FLIGHT_ID,
	CLIENT_ID AS CLIENT_ID,
	TRAVEL_CLASS_ID AS TRAVEL_CLASS_ID
FROM RESERVATIONS;

--- Naredba za dobijanje informacije o tome koji je payment vezan za rezervaciju (ne postoji direktna veza!)
SELECT PAYMENT_ID AS PAYMENT_ID FROM PAYMENTS WHERE RESERVATION_ID = ${RESERVATION_ID}

--- Naredba za dobijanje PAYMENT_DIM_ID-ja preko PAYMENT_ID:
SELECT PAYMENT_DIM_ID AS PAYMENT_DIM_ID FROM PAYMENT_DIM WHERE PAYMENT_ID = ${PAYMENT_ID}

--- Naredba za dobijanje FLIGHT_DIM_ID-ja preko FLIGHT_ID:
SELECT FLIGHT_DIM_ID AS FLIGHT_DIM_ID FROM FLIGHT_DIM WHERE FLIGHT_ID = ${FLIGHT_ID}

--- Naredba za dobijanje CLIENT_DIM_ID-ja preko CLIENT_ID:
SELECT CLIENT_DIM_ID AS CLIENT_DIM_ID FROM CLIENT_DIM WHERE CLIENT_ID = ${CLIENT_ID}

--- Naredba za dobijanje DATE_DIM_ID-ja preko DATE_ID:
SELECT DATE_DIM_ID FROM DATE_DIM WHERE RESERVATION_DATE = to_date('${RESERVATION_DATE}', 'dd-MM-yy') FETCH FIRST 1 ROW ONLY

--- Naredba za uzimanje stringa o tome o kojoj se klasi radi:
SELECT TRAVEL_CLASS_DESCRIPTION AS TRAVEL_CLASS FROM TRAVEL_CLASSES WHERE TRAVEL_CLASS_ID = ${TRAVEL_CLASS_ID}

--- Naredba za uzimanje cene leta:
SELECT TOP (1) 
	[COST]
FROM FLIGHT_COSTS WHERE FLIGHT_ID = ${FLIGHT_ID}


--- Za popunjavanje RESERVATION_FACT:
INSERT INTO RESERVATION_FACT (
	RESERVATION_ID,
	CLIENT_DIM_ID,
	DATE_DIM_ID,
	FLIGHT_DIM_ID,
	PAYMENT_DIM_ID,
	SEAT_NUMBER,
	TRAVEL_CLASS,
	PRICE,
	FLIGHT_LENGTH
) VALUES (
	${RESERVATION_ID},
	${CLIENT_DIM_ID},
	${DATE_DIM_ID},
	${FLIGHT_DIM_ID},
	${PAYMENT_DIM_ID},
	'${SEAT_NUMBER}',
	'${TRAVEL_CLASS}',
	${PRICE},
	'${FLIGHT_LENGTH}'
)

--- DateDim naredbe:
SELECT 
	DATE_DIM_ID,
	RESERVATION_DATE,
	RESERVATION_DAY_MONTH,
	RESERVATION_MONTH,
	RESERVATION_YEAR,
	RESERVATION_QUARTER
FROM DATE_DIM WHERE 
	RESERVATION_DATE = to_date('${RESERVATION_DATE}', 'dd-MM-yyyy')


--- Za dobijanje datuma poletanja i sletanja leta:
SELECT 
	FLIGHT_ID,
	FORMAT(DEPARTURE_DATE_TIME, 'dd-MM-yyyy hh:MM:ss') AS DEPARTURE_DATE_TIME,
	FORMAT(ARRIVAL_DATE_TIME, 'dd-MM-yyyy hh:MM:ss') AS ARRIVAL_DATE_TIME
FROM FLIGHTS WHERE FLIGHT_ID = ${FLIGHT_ID}

--- Reservation fact objekat iz oraclesql developer-a:
SELECT 
	RESERVATION_ID AS RESERVATION_ID_R,
	CLIENT_DIM_ID AS CLIENT_DIM_ID_R,
	DATE_DIM_ID AS DATE_DIM_ID_R,
	FLIGHT_DIM_ID AS FLIGHT_DIM_ID_R,
	PAYMENT_DIM_ID AS PAYMENT_DIM_ID_R,
	SEAT_NUMBER AS SEAT_NUMBER_R,
	TRAVEL_CLASS AS TRAVEL_CLASS_R,
	PRICE AS PRICE_R,
	FLIGHT_LENGTH AS FLIGHT_LENGTH_R
FROM RESERVATION_FACT WHERE RESERVATION_ID = ${RESERVATION_ID}

--- Update reservation fact objekat u oraclesql bazi:
UPDATE RESERVATION_FACT
SET CLIENT_DIM_ID = ${CLIENT_DIM_ID},
	DATE_DIM_ID = ${DATE_DIM_ID},
	FLIGHT_DIM_ID = ${FLIGHT_DIM_ID},
	PAYMENT_DIM_ID = ${PAYMENT_DIM_ID},
	SEAT_NUMBER = '${SEAT_NUMBER}',
	TRAVEL_CLASS = '${TRAVEL_CLASS}',
	PRICE = ${PRICE},
	FLIGHT_LENGTH = ${FLIGHT_LENGTH}
WHERE RESERVATION_ID = ${RESERVATION_ID}


--- Update u sql server
UPDATE CLIENTS
SET 
FIRST_NAME = 'Allx'
WHERE CLIENT_ID = 1